# Generated by Django 4.0.3 on 2022-08-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='email',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
