# Generated by Django 4.0.3 on 2022-08-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_recordfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordfile',
            name='date',
        ),
    ]
