# Generated by Django 4.0.3 on 2022-08-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_recordfile_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordfile',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='email',
        ),
        migrations.AddField(
            model_name='recordfile',
            name='email',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
