# Generated by Django 4.0.3 on 2022-08-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_recordfile_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='email',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
