# Generated by Django 4.0.3 on 2022-08-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userinformation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200, null=True)),
                ('blood_sugar', models.FloatField(null=True)),
                ('blood_pressure', models.CharField(max_length=100, null=True)),
                ('weight', models.FloatField(null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
