# Generated by Django 4.0.3 on 2022-08-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_foodinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200, null=True)),
                ('chicken_quantity', models.FloatField(default=0, null=True)),
                ('beef_quantity', models.FloatField(default=0, null=True)),
                ('lantil_quantity', models.FloatField(default=0, null=True)),
                ('mutton_quantity', models.FloatField(default=0, null=True)),
                ('broccoli_quantity', models.FloatField(default=0, null=True)),
                ('potatoes_quantity', models.FloatField(default=0, null=True)),
                ('corn_quantity', models.FloatField(default=0, null=True)),
                ('apple_quantity', models.FloatField(default=0, null=True)),
                ('banana_quantity', models.FloatField(default=0, null=True)),
                ('orange_quantity', models.FloatField(default=0, null=True)),
                ('rice_quantity', models.FloatField(default=0, null=True)),
                ('wheat_quantity', models.FloatField(default=0, null=True)),
                ('bread_quantity', models.FloatField(default=0, null=True)),
                ('fish_quantity', models.FloatField(default=0, null=True)),
                ('milk_quantity', models.FloatField(default=0, null=True)),
                ('yogurt_quantity', models.FloatField(default=0, null=True)),
                ('time', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Evening snack', 'Evening snack')], max_length=100, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
