# Generated by Django 4.0.3 on 2022-08-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_dietrecord_apple_unit_dietrecord_banana_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietrecord',
            old_name='apple_quantity',
            new_name='apple',
        ),
        migrations.RenameField(
            model_name='dietrecord',
            old_name='banana_quantity',
            new_name='banana',
        ),
        migrations.RenameField(
            model_name='dietrecord',
            old_name='beef_quantity',
            new_name='beef',
        ),
        migrations.RenameField(
            model_name='dietrecord',
            old_name='bread_quantity',
            new_name='bread',
        ),
        migrations.RenameField(
            model_name='dietrecord',
            old_name='broccoli_quantity',
            new_name='broccoli',
        ),
        migrations.RenameField(
            model_name='dietrecord',
            old_name='chicken_quantity',
            new_name='chicken',
        ),
        migrations.RenameField(
            model_name='dietrecord',
            old_name='corn_quantity',
            new_name='corn',
        ),
        migrations.RenameField(
            model_name='dietrecord',
            old_name='fish_quantity',
            new_name='fish',
        ),
        migrations.RenameField(
            model_name='dietrecord',
            old_name='lantil_quantity',
            new_name='lantil',
        ),
        migrations.RenameField(
            model_name='dietrecord',
            old_name='milk_quantity',
            new_name='milk',
        ),
        migrations.RenameField(
            model_name='dietrecord',
            old_name='mutton_quantity',
            new_name='mutton',
        ),
        migrations.RenameField(
            model_name='dietrecord',
            old_name='orange_quantity',
            new_name='orange',
        ),
        migrations.RenameField(
            model_name='dietrecord',
            old_name='potatoes_quantity',
            new_name='potatoes',
        ),
        migrations.RenameField(
            model_name='dietrecord',
            old_name='rice_quantity',
            new_name='rice',
        ),
        migrations.RenameField(
            model_name='dietrecord',
            old_name='wheat_quantity',
            new_name='wheat',
        ),
        migrations.RenameField(
            model_name='dietrecord',
            old_name='yogurt_quantity',
            new_name='yogurt',
        ),
    ]
