# Generated by Django 4.0.3 on 2022-08-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_dietrecord_apple_alter_dietrecord_apple_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200, null=True)),
                ('walking', models.FloatField(blank=True, default=0, null=True)),
                ('walking_unit', models.CharField(choices=[('min', 'min'), ('hour', 'hour')], default='min', max_length=100, null=True)),
                ('walking_distance', models.FloatField(blank=True, default=0, null=True)),
                ('jogging', models.FloatField(blank=True, default=0, null=True)),
                ('jogging_unit', models.CharField(choices=[('min', 'min'), ('hour', 'hour')], default='min', max_length=100, null=True)),
                ('jogging_distance', models.FloatField(blank=True, default=0, null=True)),
                ('running', models.FloatField(blank=True, default=0, null=True)),
                ('running_unit', models.CharField(choices=[('min', 'min'), ('hour', 'hour')], default='min', max_length=100, null=True)),
                ('running_distance', models.FloatField(blank=True, default=0, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
