# Generated by Django 4.0.3 on 2022-08-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_exerciserecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciserecord',
            name='jogging_distance',
            field=models.FloatField(blank=True, default='---', null=True),
        ),
        migrations.AlterField(
            model_name='exerciserecord',
            name='running_distance',
            field=models.FloatField(blank=True, default='---', null=True),
        ),
        migrations.AlterField(
            model_name='exerciserecord',
            name='walking_distance',
            field=models.FloatField(blank=True, default='---', null=True),
        ),
    ]
